benchmark_system_prompt: 
  role: system
  content: |-
    You are a helpful AI assistant.
cases:
  - case_id: "2_x_2"
    messages:
      - role: user
        content: |-
          What is 2 * 2? Respond only with the answer as an integer
    processing: 
      - function: "remove_code_fences"
        params: {}
    checks: 
      - function: "is_exact"
        params: 
          expected: "4"
    scoring:
      min: 1
  - case_id: "keep_code_fences"
    messages:
      - role: user
        content: |-
          return a json string with key "hello" and value "world" Surround the json in a triple-backtick code fence. Do not include any whitespace.
    checks: 
      - function: "is_exact"
        params: 
          expected: |-
            ```
            {"hello": "world"}
            ```
    scoring:
      min: 1
  - case_id: "hello_world_json_exact_explanation"
    messages:
      - role: user
        content: |-
          return a json string with key "hello" and value "world" Surround the json in a triple-backtick code fence. Do not include any whitespace. Include a short sentence explaining what the object is.
    processing: 
      - function: "extract_json"
    checks: 
      - function: "is_correct_json"
        params: 
          expected: 
            hello: "world"
    scoring:
      min: 1
  - case_id: "3_lines_no_the"
    messages:
      - role: user
        content: |-
          Explain how transformers work in LLMs. Your reponse should have 3 short sentences and each sentence must be on a new line. You must not use the word "the".
    processing: 
      - function: "remove_code_fences"
        params: {}
    checks:
      - function: "count_lines"
        params:
          expected: "3"
      - function: "contains_word"
        params:
          substring: "the"
          expected: "False"
    scoring:
      min: 2